jira:
  image: cptactionhank/atlassian-jira:7.2.6
  restart: always
  links:
    - database
  volumes:
    - ~/workspace/docker/atlassian/jira:/var/atlassian/jira

confluence:
  image: cptactionhank/atlassian-confluence:6.0.2
  restart: always
  links:
    - database
  volumes:
    - ~/workspace/docker/atlassian/confluence:/var/atlassian/confluence

bitbucket:
  image: bitbucket-server:4.10.1
  restart: always
  links:
    - database
  volumes:
    - ~/workspace/docker/atlassian/bitbucket:/var/atlassian/application-data/bitbucket

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
    - PMA_ARBITRARY=1
  restart: always
  links:
    - database
  environment:
    PMA_USER: root
    PMA_PASSWORD: passpass 

database:
  image: mysql:5.6
  restart: always
  environment: 
    MYSQL_ROOT_PASSWORD: passpass
  volumes:
    - ~/workspace/docker/mysql:/var/lib/mysql

nginx:
  image: nginx
  restart: always
  ports:
    - "80:80"
  links:
    - jira
    - confluence
    - bitbucket
  volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro