jira:
  image: cptactionhank/atlassian-jira:7.0.5
  restart: always
  links:
    - database
  volumes:
    - ~/workspace/docker/atlassian/jira:/var/atlassian/jira

confluence:
  image: cptactionhank/atlassian-confluence:5.9.4
  restart: always
  links:
    - database
  volumes:
    - ~/workspace/docker/atlassian/confluence:/var/atlassian/confluence

bitbucket:
  image: atlassian/bitbucket-server
  restart: always
  links:
    - database
  volumes:
    - ~/workspace/docker/atlassian/bitbucket:/var/atlassian/application-data/bitbucket

database:
  image: postgres:9.4
  restart: always
  volumes:
    - ~/workspace/docker/postgres:/var/lib/postgresql/data

nginx:
  image: nginx
  restart: always
  ports:
    - "80:80"
  links:
    - jira
    - confluence
    - bitbucket
  volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro